import * as fs from 'fs'
import * as path from 'path'

interface DocLink
{
  title: string
  path: string
}

interface DocFolder
{
  name: string
  folder: string
}

const docFolders: DocFolder[] = 
[
  {
    name: 'Wiki',
    folder: '/wiki'
  }
]

const docLinks: DocLink[] = 
[
  {
    title: 'Yanorra',
    path: '/Yanorra.html'
  }
]

const excludedFiles = ['TEMPLATE']

const isExcludedFile = (fileName: string): boolean =>
{
  const normalizedFileName = fileName.toLowerCase()
  return excludedFiles.some((excludedFile) =>
  {
    return normalizedFileName.startsWith(excludedFile.toLowerCase())
  })
}

// Scan folders for HTML files
docFolders.forEach((docFolder) => 
{
  console.log(`Scanning folder: ${docFolder.folder} for HTML files...`)
  const folderPath = path.join(process.cwd(), 'dist', docFolder.folder)
  try 
  {
    const files = fs.readdirSync(folderPath)
    files.forEach((file: string) => 
    {
      if (file.toLowerCase().endsWith('.html') 
        && !isExcludedFile(file))
      {
        console.log(`Adding file: ${file} from folder: ${docFolder.folder}`)

        docLinks.push(
        {
          title: file.replace(/\.html$/i, '').replace(/_/g, ' '),  
          path: `${docFolder.folder}/${file}`
        })
      }
    })
  } 
  catch (err) 
  {
    console.warn(`Warning: Could not read folder ${folderPath}`)
  }
})

// Generate the TypeScript config file
const output = `// This file is auto-generated by generate-docs-config.ts
// Do not edit manually - it will be overwritten

export interface DocLink
{
  title: string
  path: string
}

export const docLinks: DocLink[] = ${JSON.stringify(docLinks, null, 2)}
`

fs.writeFileSync(path.join(process.cwd(), 'src', 'docsConfig.ts'), output)
console.log('✓ Generated docsConfig.ts')
