import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
// import { convertMarkdownFiles } from '../vite-plugin-markdown'

interface DocLink
{
  title: string
  path: string
}

// interface DocFolder
// {
//   name: string
//   folder: string
// }

// const docFolders: DocFolder[] = 
// [
//   {
//     name: 'Wiki',
//     folder: 'wiki'
//   }
// ]

const docLinks: DocLink[] = 
[
  {
    title: 'Yanorra',
    path: '/Yanorra.html'
  }
]

const excludedFiles = ['TEMPLATE']

const isExcludedFile = (fileName: string): boolean =>
{
  const normalizedFileName = fileName.toLowerCase()
  return excludedFiles.some((excludedFile) =>
  {
    return normalizedFileName.startsWith(excludedFile.toLowerCase())
  })
}

const generateDocLinks = async (): Promise<void> =>
{
  const __dirname = path.dirname(fileURLToPath(import.meta.url))
  const wikiDir = path.resolve(__dirname, '../Yanorra/Wiki')

  if (!fs.existsSync(wikiDir))
  {
    console.warn(`Warning: Wiki folder not found at ${wikiDir}`)
    return
  }

  const files = fs.readdirSync(wikiDir)
  files.forEach((file) =>
  {
    if (!isExcludedFile(file))
    {
      console.log(`Adding file: ${file} from Wiki folder`)

      docLinks.push(
      {
        title: file.replace(/\.md$/i, '').replace(/_/g, ' '), 
        path: `/wiki/${file.replace(/\.md$/i, '')}`
      })
    }
  })
}

const run = async (): Promise<void> =>
{
  // await convertMarkdownFiles()

  // Scan folders for HTML files
  // docFolders.forEach((docFolder) => 
  // {
  //   console.log(`Scanning folder: ${docFolder.folder} for HTML files...`)
  //   const folderPath = path.join(process.cwd(), 'public', docFolder.folder)
  //   try 
  //   {
  //     const files = fs.readdirSync(folderPath)
  //     files.forEach((file: string) => 
  //     {
  //       if (file.toLowerCase().endsWith('.html') 
  //         && !isExcludedFile(file))
  //       {
  //         console.log(`Adding file: ${file} from folder: ${docFolder.folder}`)

  //         docLinks.push(
  //         {
  //           title: file.replace(/\.html$/i, '').replace(/_/g, ' '),  
  //           path: `/${docFolder.folder}/${file.replace(/\.html$/i, '')}`
  //         })
  //       }
  //     })
  //   } 
  //   catch (err) 
  //   {
  //     console.warn(`Warning: Could not read folder ${folderPath}`)
  //   }
  // })

  await generateDocLinks();

  // Generate the TypeScript config file
  const output = `// This file is auto-generated by prebuild-docs.ts
// Do not edit manually - it will be overwritten

export interface DocLink
{
  title: string
  path: string
}

export const docLinks: DocLink[] = ${JSON.stringify(docLinks, null, 2)}
`

  const outputPath = path.join(process.cwd(), 'src', 'docsConfig.ts')
  if (fs.existsSync(outputPath))
  {
    console.log('Existing docsConfig.ts found, deleting...')
    fs.unlinkSync(outputPath)
  }
  fs.writeFileSync(outputPath, output)
  console.log('✓ Generated docsConfig.ts')

  // console.debug(fs.readFileSync(outputPath, 'utf-8'))
}

run().catch((err) =>
{
  console.error(err)
  process.exit(1)
})
