import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
import { parse as parseYaml } from 'yaml'

interface DocLink
{
    title: string
    path: string
}

const docLinks: DocLink[] = []
const nationLinks: DocLink[] = []
const excludedFiles = ['TEMPLATE']

const isExcludedFile = (fileName: string): boolean =>
{
    const normalizedFileName = fileName.toLowerCase()
    return excludedFiles.some((excludedFile) =>
    {
        return normalizedFileName.startsWith(excludedFile.toLowerCase())
    })
}

const FRONT_MATTER_PATTERN = /^---\s*\r?\n([\s\S]*?)\r?\n---\s*(?:\r?\n|$)/

const isNationFile = (filePath: string, fileName: string): boolean =>
{
    const fileContents = fs.readFileSync(filePath, 'utf-8')
    const match = fileContents.match(FRONT_MATTER_PATTERN)

    if (!match)
    {
        return false
    }

    const yamlSource = match[1]

    try
    {
        const parsedYaml = parseYaml(yamlSource)
        // console.log(`[frontmatter] ${fileName}`)
        // console.log(parsedYaml)
        return parsedYaml.subcategory === 'nations'
    }
    catch (error)
    {
        console.warn(`[frontmatter] Failed to parse YAML in ${fileName}`)
        if (error instanceof Error)
        {
            console.warn(error.message)
        }

        return false
    }
}

const generateDocLinks = async (): Promise<void> =>
{
    const __dirname = path.dirname(fileURLToPath(import.meta.url))

    // TODO: __dirname may not be defined because of ES modules - need to use import.meta.url instead
    const wikiDir = path.resolve(__dirname, '../yanorra-wiki/Wiki')

    if (!fs.existsSync(wikiDir))
    {
        console.warn(`Warning: Wiki folder not found at ${wikiDir}`)
        return
    }

    const files = fs.readdirSync(wikiDir)
    files.forEach((file) =>
    {
        const isMarkdownFile = file.toLowerCase().endsWith('.md')

        if (!isMarkdownFile)
        {
            return
        }

        if (!isExcludedFile(file))
        {
            console.log(`Adding file: ${file} from Wiki folder`)
            const filePath = path.join(wikiDir, file)
            if (isNationFile(filePath, file))
            {
                nationLinks.push(
                    {
                        title: file.replace(/\.md$/i, '').replace(/_/g, ' '),
                        path: `/wiki/${file.replace(/\.md$/i, '')}`
                    })
            }

            docLinks.push(
                {
                    title: file.replace(/\.md$/i, '').replace(/_/g, ' '),
                    path: `/wiki/${file.replace(/\.md$/i, '')}`
                })
        }
    })
}

const run = async (): Promise<void> =>
{
    await generateDocLinks();

    // Generate the TypeScript config file
    const output = `// This file is auto-generated by prebuild-docs.ts
// Do not edit manually - it will be overwritten

export interface DocLink
{
  title: string
  path: string
}

export const docLinks: DocLink[] = ${JSON.stringify(docLinks, null, 2)}
export const nationLinks: DocLink[] = ${JSON.stringify(nationLinks, null, 2)}
`

    const outputPath = path.join(process.cwd(), 'src', 'docsConfig.ts')
    if (fs.existsSync(outputPath))
    {
        console.log('Existing docsConfig.ts found, deleting...')
        fs.unlinkSync(outputPath)
    }
    fs.writeFileSync(outputPath, output)
    console.log('✓ Generated docsConfig.ts')

    // console.debug(fs.readFileSync(outputPath, 'utf-8'))
}

run().catch((err) =>
{
    console.error(err)
    process.exit(1)
})
