import * as fs from 'fs'
import * as path from 'path'
import { execSync } from 'child_process'
import { convertAsciidocFiles } from '../vite-plugin-asciidoc'
import { convertMarkdownFiles } from '../vite-plugin-markdown'

interface DocLink
{
  title: string
  path: string
}

interface DocFolder
{
  name: string
  folder: string
}

const docFolders: DocFolder[] = 
[
  {
    name: 'Wiki',
    folder: 'wiki'
  }
]

const docLinks: DocLink[] = 
[
  {
    title: 'Yanorra',
    path: '/Yanorra.html'
  }
]

const excludedFiles = ['TEMPLATE']

const isExcludedFile = (fileName: string): boolean =>
{
  const normalizedFileName = fileName.toLowerCase()
  return excludedFiles.some((excludedFile) =>
  {
    return normalizedFileName.startsWith(excludedFile.toLowerCase())
  })
}

const getYanorraRepoDir = (): string | null =>
{
  const currentDir = process.cwd()
  const currentGitDir = path.join(currentDir, '.git')
  if (path.basename(currentDir).toLowerCase() === 'yanorra' && fs.existsSync(currentGitDir))
  {
    return currentDir
  }

  const repoDir = path.join(currentDir, 'Yanorra')
  const repoGitDir = path.join(repoDir, '.git')
  if (fs.existsSync(repoGitDir))
  {
    return repoDir
  }

  return null
}

const updateYanorraRepo = (): void =>
{
  const repoDir = getYanorraRepoDir()
  if (!repoDir)
  {
    console.warn('Warning: Yanorra repo not found, skipping git pull --rebase')
    return
  }

  const originalDir = process.cwd()
  const shouldChangeDir = path.resolve(originalDir) !== path.resolve(repoDir)

  if (shouldChangeDir)
  {
    console.log(`Changing directory to ${repoDir}`)
    process.chdir(repoDir)
  }

  try
  {
    console.log('Running git pull --rebase in Yanorra repo...')
    execSync('git pull --rebase', { stdio: 'inherit' })
  }
  catch (err)
  {
    console.warn('Warning: git pull --rebase failed in Yanorra repo')
  }
  finally
  {
    if (shouldChangeDir)
    {
      console.log(`Changing directory back to ${originalDir}`)
      process.chdir(originalDir)
    }
  }
}

const run = async (): Promise<void> =>
{
  updateYanorraRepo()

  await convertAsciidocFiles()
  await convertMarkdownFiles()

  // Scan folders for HTML files
  docFolders.forEach((docFolder) => 
  {
    console.log(`Scanning folder: ${docFolder.folder} for HTML files...`)
    const folderPath = path.join(process.cwd(), 'public', docFolder.folder)
    try 
    {
      const files = fs.readdirSync(folderPath)
      files.forEach((file: string) => 
      {
        if (file.toLowerCase().endsWith('.html') 
          && !isExcludedFile(file))
        {
          console.log(`Adding file: ${file} from folder: ${docFolder.folder}`)

          docLinks.push(
          {
            title: file.replace(/\.html$/i, '').replace(/_/g, ' '),  
            path: `/${docFolder.folder}/${file}`
          })
        }
      })
    } 
    catch (err) 
    {
      console.warn(`Warning: Could not read folder ${folderPath}`)
    }
  })

  // Generate the TypeScript config file
  const output = `// This file is auto-generated by prebuild-docs.ts
// Do not edit manually - it will be overwritten

export interface DocLink
{
  title: string
  path: string
}

export const docLinks: DocLink[] = ${JSON.stringify(docLinks, null, 2)}
`

  const outputPath = path.join(process.cwd(), 'src', 'docsConfig.ts')
  if (fs.existsSync(outputPath))
  {
    console.log('Existing docsConfig.ts found, deleting...')
    fs.unlinkSync(outputPath)
  }
  fs.writeFileSync(outputPath, output)
  console.log('✓ Generated docsConfig.ts')

  // console.debug(fs.readFileSync(outputPath, 'utf-8'))
}

run().catch((err) =>
{
  console.error(err)
  process.exit(1)
})
