// This file is auto-generated by generate-docs-config.ts
// Do not edit manually - it will be overwritten

export interface DocLink
{
  title: string
  path: string
}

export const docLinks: DocLink[] = [
  {
    "title": "Yanorra",
    "path": "/Yanorra.html"
  },
  {
    "title": "Barrel",
    "path": "./wiki/Barrel.html"
  },
  {
    "title": "Bharim Islands",
    "path": "./wiki/Bharim_Islands.html"
  },
  {
    "title": "Bibi Shirif",
    "path": "./wiki/Bibi_Shirif.html"
  },
  {
    "title": "Duvessa",
    "path": "./wiki/Duvessa.html"
  },
  {
    "title": "Endotoku",
    "path": "./wiki/Endotoku.html"
  },
  {
    "title": "Hav",
    "path": "./wiki/Hav.html"
  },
  {
    "title": "Land of Water",
    "path": "./wiki/Land_of_Water.html"
  },
  {
    "title": "Lo-Disporum",
    "path": "./wiki/Lo-Disporum.html"
  },
  {
    "title": "Noxoch Isle",
    "path": "./wiki/Noxoch_Isle.html"
  },
  {
    "title": "Obetoku",
    "path": "./wiki/Obetoku.html"
  },
  {
    "title": "Ronobetu",
    "path": "./wiki/Ronobetu.html"
  },
  {
    "title": "S Tsutodo",
    "path": "./wiki/S_Tsutodo.html"
  },
  {
    "title": "Saint Aveline",
    "path": "./wiki/Saint_Aveline.html"
  },
  {
    "title": "Samerland",
    "path": "./wiki/Samerland.html"
  },
  {
    "title": "Stanshonia",
    "path": "./wiki/Stanshonia.html"
  },
  {
    "title": "The Drift",
    "path": "./wiki/The_Drift.html"
  },
  {
    "title": "The Farlands",
    "path": "./wiki/The_Farlands.html"
  },
  {
    "title": "The Three Sisters",
    "path": "./wiki/The_Three_Sisters.html"
  },
  {
    "title": "Thornbelt",
    "path": "./wiki/Thornbelt.html"
  },
  {
    "title": "Totoku",
    "path": "./wiki/Totoku.html"
  },
  {
    "title": "Tsutodo",
    "path": "./wiki/Tsutodo.html"
  },
  {
    "title": "Velu",
    "path": "./wiki/Velu.html"
  },
  {
    "title": "Westlands",
    "path": "./wiki/Westlands.html"
  }
]
