// This file is auto-generated by generate-docs-config.ts
// Do not edit manually - it will be overwritten

export interface DocLink
{
  title: string
  path: string
}

export const docLinks: DocLink[] = [
  {
    "title": "Yanorra",
    "path": "/Yanorra.html"
  },
  {
    "title": "Barrel",
    "path": "/wiki/Barrel.html"
  },
  {
    "title": "Bharim_Islands",
    "path": "/wiki/Bharim_Islands.html"
  },
  {
    "title": "Bibi_Shirif",
    "path": "/wiki/Bibi_Shirif.html"
  },
  {
    "title": "Duvessa",
    "path": "/wiki/Duvessa.html"
  },
  {
    "title": "Endotoku",
    "path": "/wiki/Endotoku.html"
  },
  {
    "title": "Hav",
    "path": "/wiki/Hav.html"
  },
  {
    "title": "Land_of_Water",
    "path": "/wiki/Land_of_Water.html"
  },
  {
    "title": "Lo-Disporum",
    "path": "/wiki/Lo-Disporum.html"
  },
  {
    "title": "Noxoch_Isle",
    "path": "/wiki/Noxoch_Isle.html"
  },
  {
    "title": "Obetoku",
    "path": "/wiki/Obetoku.html"
  },
  {
    "title": "Ronobetu",
    "path": "/wiki/Ronobetu.html"
  },
  {
    "title": "S_Tsutodo",
    "path": "/wiki/S_Tsutodo.html"
  },
  {
    "title": "Samerland",
    "path": "/wiki/Samerland.html"
  },
  {
    "title": "Stanshonia",
    "path": "/wiki/Stanshonia.html"
  },
  {
    "title": "TEMPLATE",
    "path": "/wiki/TEMPLATE.html"
  },
  {
    "title": "The_Drift",
    "path": "/wiki/The_Drift.html"
  },
  {
    "title": "The_Three_Sisters",
    "path": "/wiki/The_Three_Sisters.html"
  },
  {
    "title": "Thornbelt",
    "path": "/wiki/Thornbelt.html"
  },
  {
    "title": "Totoku",
    "path": "/wiki/Totoku.html"
  },
  {
    "title": "Tsutodo",
    "path": "/wiki/Tsutodo.html"
  },
  {
    "title": "Velu",
    "path": "/wiki/Velu.html"
  },
  {
    "title": "Westlands",
    "path": "/wiki/Westlands.html"
  }
]
